#!/usr/bin/env bash

echo "Starting Seafile"

for i in {1..20}; do
  echo "$i..."
  sleep 1
done

if (( $RANDOM % 2 )); then
  echo "Finished running"
else
  echo "Oops, catastrophic failure" 1>&2
  exit 83
fi
